# Generated by Django 3.1.6 on 2021-03-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ya", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="ruleset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="ya.ruleset",
            ),
        ),
    ]
