# Generated by Django 3.1.6 on 2021-03-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ya", "0002_auto_20210314_1621"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="namespace",
        ),
    ]