# Generated by Django 3.1.6 on 2021-03-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ya", "0003_remove_rule_namespace"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="compiled",
            field=models.BooleanField(default=False),
        ),
    ]
