# Generated by Django 3.2.4 on 2021-06-18 09:47

from django.db import migrations, models


def set_cloned_true(apps, schema_editor):
    Ruleset = apps.get_model("ya", "ruleset")
    for ruleset in Ruleset.objects.all():
        ruleset.cloned = True
        ruleset.save()


class Migration(migrations.Migration):

    dependencies = [
        ("ya", "0004_rule_compiled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="ruleset",
            name="deleted",
        ),
        migrations.AddField(
            model_name="ruleset",
            name="cloned",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_cloned_true),
    ]
