# Generated by Django 3.2.4 on 2021-06-18 09:47

from django.db import migrations, models
from orochi.ya.schema import RuleIndex


def set_cloned_true(apps, schema_editor):
    Ruleset = apps.get_model("ya", "Ruleset")
    for ruleset in Ruleset.objects.all():
        ruleset.cloned = True
        ruleset.save()

    Rule = apps.get_model("ya", "Rule")
    rule_index = RuleIndex()
    for rule in Rule.objects.exclude(enabled=False).exclude(ruleset__enabled=False):
        rule_index.add_document(
            rule.path, rule.ruleset.name, rule.ruleset.description, rule.pk
        )


class Migration(migrations.Migration):

    dependencies = [
        ("ya", "0004_rule_compiled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="ruleset",
            name="deleted",
        ),
        migrations.AddField(
            model_name="ruleset",
            name="cloned",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_cloned_true),
    ]
