# Generated by Django 5.1 on 2024-09-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ya", "0005_auto_20210618_0947"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="rule",
            field=models.TextField(blank=True, null=True),
        ),
    ]
