# Generated by Django 5.1 on 2024-09-04 11:50

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ya", "0006_rule_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.SearchVector(
                        "rule", config="english"
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "path", config="english"
                    ),
                    django.contrib.postgres.search.SearchConfig("english"),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
    ]
