# Generated by Django 6.1.1 on 2026-09-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ya", "0008_rule_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleset",
            name="auto_update",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="last_sync_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="last_sync_status",
            field=models.CharField(default="IDLE", max_length=50),
        ),
    ]
