# Generated by Django 3.1 on 2020-08-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='services',
        ),
    ]
