# Generated by Django 3.2 on 2020-06-11 07:36

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dump",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operating_system",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Linux"),
                            (2, "Windows"),
                            (3, "Mac"),
                            (4, "Other"),
                        ],
                        default=1,
                    ),
                ),
                ("upload", models.FileField(upload_to="uploads")),
                ("name", models.CharField(max_length=250, unique=True)),
                ("index", models.CharField(blank=True, max_length=250, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "color",
                    colorfield.fields.ColorField(default="#FF0000", max_length=18),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Created"), (2, "Completed"), (3, "Deleted")],
                        default=1,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dumps",
                "permissions": (("can_see", "Can See"),),
            },
        ),
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                (
                    "operating_system",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Linux"),
                            (2, "Windows"),
                            (3, "Mac"),
                            (4, "Other"),
                        ],
                        default=1,
                    ),
                ),
                ("disabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Empty"),
                            (2, "Success"),
                            (3, "Unsatisfied"),
                            (4, "Error"),
                            (5, "Disabled"),
                        ],
                        default=1,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "dump",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.dump"
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.plugin"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dump",
            name="plugins",
            field=models.ManyToManyField(through="website.Result", to="website.Plugin"),
        ),
    ]
