# Generated by Django 3.0.5 on 2020-05-15 16:08

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads')),
                ('name', models.CharField(max_length=250)),
                ('index', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Completed'), (3, 'Deleted')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analyses',
                'permissions': (('can_see', 'Can See'),),
            },
        ),
    ]
