# Generated by Django 3.2 on 2020-06-11 07:42

from django.db import migrations
import volatility.plugins

from volatility import framework
from volatility.framework import contexts


def load_plugins(apps, schema_editor):
    Plugin = apps.get_model("website", "Plugin")

    ctx = contexts.Context()
    failures = framework.import_files(volatility.plugins, True)
    for plugin_name in framework.list_plugins():
        if plugin_name.startswith("linux"):
            plugin = Plugin(name=plugin_name, operating_system=1)
        elif plugin_name.startswith("windows"):
            plugin = Plugin(name=plugin_name, operating_system=2)
        elif plugin_name.startswith("mac"):
            plugin = Plugin(name=plugin_name, operating_system=3)
        else:
            plugin = Plugin(name=plugin_name, operating_system=4)
        plugin.save()


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_plugins),
    ]
