# Generated by Django 3.2 on 2020-07-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='local_dump',
            field=models.BooleanField(default=False),
        ),
    ]
