# Generated by Django 3.0.5 on 2020-06-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200604_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='operating_system',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Linux'), (2, 'Windows'), (3, 'Mac'), (4, 'Other')], default=1),
        ),
    ]
