# Generated by Django 3.2 on 2020-07-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_plugin_local_dump'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250, unique=True)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('clamav', models.CharField(blank=True, max_length=250, null=True)),
                ('vt_report', models.CharField(blank=True, max_length=250, null=True)),
                ('vt_score', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.result')),
            ],
        ),
    ]
