# Generated by Django 3.2 on 2020-07-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_extracteddump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dump',
            name='index',
            field=models.CharField(default='smile', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dump',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Completed'), (3, 'Deleted'), (4, 'Error')], default=1),
        ),
    ]
