# Generated by Django 3.0.5 on 2020-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200604_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
