# Generated by Django 3.0.5 on 2020-06-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_plugin_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Empty'), (2, 'Success'), (3, 'Unsatisfied'), (4, 'Error'), (5, 'Disabled')], default=1),
        ),
    ]
