# Generated by Django 3.1 on 2020-08-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_result_parameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplugin',
            old_name='disabled',
            new_name='automatic',
        ),
    ]
