# Generated by Django 3.1 on 2020-08-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200804_1422'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('dump', 'plugin')},
        ),
    ]
