# Generated by Django 3.1 on 2020-08-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200804_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userplugin',
            options={'ordering': ('plugin__name',)},
        ),
    ]
