# Generated by Django 3.1 on 2020-08-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200805_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.PositiveIntegerField(choices=[(1, 'VirusTotal')]),
        ),
    ]
