# Generated by Django 3.1 on 2020-08-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200805_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.PositiveIntegerField(choices=[(1, 'VirusTotal')], unique=True),
        ),
    ]
