# Generated by Django 3.1 on 2020-08-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200805_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='proxy',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
