# Generated by Django 3.1 on 2020-08-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_service_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='clamav_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plugin',
            name='regipy_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plugin',
            name='vt_check',
            field=models.BooleanField(default=False),
        ),
    ]
