# Generated by Django 3.1 on 2020-08-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200826_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
