# Generated by Django 3.1 on 2020-08-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20200827_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddump',
            name='reg_array',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
