# Generated by Django 3.1.1 on 2020-09-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_extracteddump_reg_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracteddump',
            name='vt_score',
        ),
        migrations.AlterField(
            model_name='extracteddump',
            name='vt_report',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
