# Generated by Django 3.1.1 on 2020-09-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20200930_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='operating_system',
            field=models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('Mac', 'Mac'), ('Other', 'Other')], default='Linux', max_length=10),
        ),
    ]
