# Generated by Django 3.1.3 on 2020-11-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_dump_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dump',
            name='missing_symbols',
            field=models.BooleanField(default=False),
        ),
    ]
