# Generated by Django 3.1.5 on 2021-01-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_dump_missing_symbols'),
    ]

    operations = [
        migrations.AddField(
            model_name='dump',
            name='suggested_symbols_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
