# Generated by Django 3.1.5 on 2021-01-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0027_dump_suggested_symbols_path"),
    ]

    operations = []
