# Generated by Django 3.1.6 on 2021-02-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0029_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="query",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="star",
            field=models.BooleanField(default=False),
        ),
    ]
