# Generated by Django 3.1.6 on 2021-02-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0031_auto_20210212_1319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.PositiveIntegerField(
                choices=[(1, "VirusTotal"), (2, "MISP")], unique=True
            ),
        ),
    ]
