# Generated by Django 3.1.6 on 2021-02-18 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orochi.website.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0032_auto_20210215_1553"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("public", models.BooleanField(default=False)),
                (
                    "download",
                    models.FileField(
                        upload_to=orochi.website.models.user_directory_path
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]