# Generated by Django 3.1.6 on 2021-03-03 15:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0033_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dump",
            name="suggested_symbols_path",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=1000, null=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]