# Generated by Django 3.2.9 on 2021-11-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0037_plugin_yara_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracteddump",
            name="md5",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
