# Generated by Django 3.2.9 on 2021-11-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0038_extracteddump_md5"),
    ]

    operations = [
        migrations.AddField(
            model_name="dump",
            name="md5",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="dump",
            name="sha256",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="dump",
            name="size",
            field=models.IntegerField(null=True),
        ),
    ]
