# Generated by Django 4.0.2 on 2022-02-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0040_plugin_local_plugin_local_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dump",
            name="size",
            field=models.BigIntegerField(null=True),
        ),
    ]
