# Generated by Django 4.2.6 on 2023-10-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0043_alter_bookmark_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugin",
            name="maxmind_check",
            field=models.BooleanField(default=False),
        ),
    ]
