# Generated by Django 5.0.1 on 2024-01-29 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("website", "0044_plugin_maxmind_check")]
    operations = [migrations.DeleteModel(name="ExtractedDump")]
