# Generated by Django 5.0.1 on 2024-01-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("website", "0045_delete_extracteddump")]

    operations = [
        migrations.AddField(
            model_name="dump",
            name="comment",
            field=models.TextField(blank=True, null=True),
        )
    ]
