# Generated by Django 5.0.1 on 2024-01-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("website", "0046_dump_comment")]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.PositiveIntegerField(
                choices=[(1, "VirusTotal"), (2, "MISP"), (3, "MAXMIND")], unique=True
            ),
        )
    ]
