# Generated by Django 5.0.1 on 2024-02-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0047_alter_service_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="dump",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
