# Generated by Django 5.0.1 on 2024-02-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0050_folder_dump_folder"),
    ]
    operations = [
        migrations.RemoveField(model_name="dump", name="missing_symbols"),
        migrations.AlterField(
            model_name="dump",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Created"),
                    (2, "Completed"),
                    (3, "Deleted"),
                    (4, "Error"),
                    (5, "Missing Symbols"),
                ],
                default=1,
            ),
        ),
    ]
