# Generated by Django 5.0.3 on 2024-03-20 13:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0053_create_default_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="dump",
            name="regipy_plugins",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(blank=True, null=True),
                blank=True,
                null=True,
                size=None,
                default=list,
            ),
        ),
    ]
