# Generated by Django 5.0.3 on 2024-04-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0054_dump_regipy_plugins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dump",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Created"),
                    (2, "Unzipping"),
                    (3, "Completed"),
                    (4, "Deleted"),
                    (5, "Error"),
                    (6, "Missing Symbols"),
                ],
                default=1,
            ),
        ),
    ]
