# Generated by Django 5.1.1 on 2024-09-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0058_remove_result_value_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plugin",
            name="yara_check",
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.PositiveIntegerField(
                choices=[(1, "VirusTotal"), (2, "MISP")], unique=True
            ),
        ),
    ]
