# Generated by Django 5.2.1 on 2025-05-12 11:59

import colorfield.fields
import orochi.website.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0059_remove_plugin_yara_check_alter_service_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dump",
            name="color",
            field=colorfield.fields.ColorField(
                default=orochi.website.models.random_color,
                image_field=None,
                max_length=25,
                samples=[
                    ("#e6194B", "Red"),
                    ("#3cb44b", "Green"),
                    ("#ffe119", "Yellow"),
                    ("#4363d8", "Blue"),
                    ("#f58231", "Orange"),
                    ("#911eb4", "Purple"),
                    ("#42d4f4", "Cyan"),
                    ("#f032e6", "Magenta"),
                    ("#bfef45", "Lime"),
                    ("#fabed4", "Pink"),
                    ("#469990", "Teal"),
                    ("#dcbeff", "Lavender"),
                    ("#9A6324", "Brown"),
                    ("#fffac8", "Beige"),
                    ("#800000", "Maroon"),
                    ("#aaffc3", "Mint"),
                    ("#808000", "Olive"),
                    ("#ffd8b1", "Apricot"),
                    ("#000075", "Navy"),
                    ("#a9a9a9", "Grey"),
                ],
            ),
        ),
    ]