# Generated by Django 6.0.7 on 2026-07-29 06:36

import colorfield.fields
import django.db.models.deletion
import orochi.website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0061_alter_bookmark_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dump",
            name="color",
            field=colorfield.fields.ColorField(
                default=orochi.website.models.random_color,
                image_field=None,
                max_length=25,
                samples=[
                    ("#e6194B", "Red"),
                    ("#3cb44b", "Green"),
                    ("#ffe119", "Yellow"),
                    ("#4363d8", "Blue"),
                    ("#f58231", "Orange"),
                    ("#911eb4", "Purple"),
                    ("#42d4f4", "mist"),
                    ("#f032e6", "Magenta"),
                    ("#bfef45", "Lime"),
                    ("#fabed4", "Pink"),
                    ("#469990", "Teal"),
                    ("#dcbeff", "Lavender"),
                    ("#9A6324", "Brown"),
                    ("#fffac8", "Beige"),
                    ("#800000", "Maroon"),
                    ("#aaffc3", "Mint"),
                    ("#808000", "Olive"),
                    ("#ffd8b1", "Apricot"),
                    ("#000075", "Navy"),
                    ("#a9a9a9", "Grey"),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Open", max_length=50)),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases",
                        to="website.folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "user")},
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="website.case",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "case")},
            },
        ),
    ]