# Generated by Django 6.0.7 on 2026-07-29 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0062_alter_dump_color_case_evidence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="evidence",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="case",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                related_name="collaborating_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="dump",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidences",
                to="website.dump",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="extracted_file",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="evidence",
            name="plugin",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="evidence",
            name="result_row",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
