# Generated by Django 6.0.7 on 2026-07-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0066_case_is_ctf"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("template", models.FileField(upload_to="report_templates/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.PositiveIntegerField(
                choices=[(1, "VirusTotal"), (2, "MISP"), (3, "Ollama")], unique=True
            ),
        ),
    ]
