# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0067_reporttemplate_alter_service_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(default="Submitted", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
