# Generated by Django 6.1.1 on 2026-09-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0070_host_dump_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "VirusTotal"),
                    (2, "MISP"),
                    (3, "Ollama"),
                    (4, "Webhook"),
                    (5, "Slack"),
                    (6, "Email"),
                ],
                unique=True,
            ),
        ),
    ]