# Generated by Django 6.1.1 on 2026-09-07 08:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0071_alter_host_id_alter_service_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.SearchVector(
                        "name", config="english"
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "description", config="english"
                    ),
                    django.contrib.postgres.search.SearchConfig("english"),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddField(
            model_name="dump",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.CombinedSearchVector(
                                django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.SearchVector(
                                        "name", config="english"
                                    ),
                                    "||",
                                    django.contrib.postgres.search.SearchVector(
                                        "comment", config="english"
                                    ),
                                    django.contrib.postgres.search.SearchConfig(
                                        "english"
                                    ),
                                ),
                                "||",
                                django.contrib.postgres.search.SearchVector(
                                    "description", config="english"
                                ),
                                django.contrib.postgres.search.SearchConfig("english"),
                            ),
                            "||",
                            django.contrib.postgres.search.SearchVector(
                                "banner", config="english"
                            ),
                            django.contrib.postgres.search.SearchConfig("english"),
                        ),
                        "||",
                        django.contrib.postgres.search.SearchVector(
                            "md5", config="english"
                        ),
                        django.contrib.postgres.search.SearchConfig("english"),
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "sha256", config="english"
                    ),
                    django.contrib.postgres.search.SearchConfig("english"),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="case_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dump",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="dump_gin_idx"
            ),
        ),
    ]
