# Generated by Django 6.1.1 on 2026-09-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0072_case_search_vector_dump_search_vector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("Closed", "Closed"),
                ],
                default="Open",
                max_length=50,
            ),
        ),
    ]
