# Generated by Django 6.1.1 on 2026-09-08 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0074_valueannotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="dump",
            name="risk_score",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="DumpSecret",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("aws", "AWS Credentials"),
                            ("private_key", "Private Key (PEM/SSH)"),
                            ("jwt", "JWT Token"),
                            ("api_key", "API Key / Token"),
                            ("db_uri", "Database Connection URI"),
                            ("password", "Password / Generic Credential"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rule_name", models.CharField(max_length=150)),
                ("matched_data", models.TextField()),
                ("masked_data", models.TextField()),
                ("offset", models.CharField(blank=True, max_length=50, null=True)),
                ("pid", models.IntegerField(blank=True, null=True)),
                (
                    "process_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dump",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="website.dump",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["dump", "category"],
                        name="website_dum_dump_id_302a24_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TriageFinding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_id", models.CharField(max_length=100)),
                ("rule_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                            ("Info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField(default=10)),
                (
                    "mitre_technique",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField()),
                ("evidence_snippet", models.TextField(blank=True, null=True)),
                ("entity", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dump",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triage_findings",
                        to="website.dump",
                    ),
                ),
            ],
            options={
                "ordering": ("-score", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["dump", "severity"],
                        name="website_tri_dump_id_b1d6d8_idx",
                    )
                ],
            },
        ),
    ]
