# Generated by Django 6.1.1 on 2026-09-09 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0076_plugin_min_role_userplugin_can_execute"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DumpNarrative",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(default="llama3.2:1b", max_length=100)),
                ("raw_narrative", models.TextField()),
                ("formatted_narrative", models.TextField()),
                (
                    "evidence_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("citations", models.JSONField(blank=True, default=list)),
                ("hallucination_check", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dump_narratives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dump",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narratives",
                        to="website.dump",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["dump", "-created_at"],
                        name="website_dum_dump_id_b4d008_idx",
                    )
                ],
            },
        ),
    ]
