# Generated by Django 6.1.1 on 2026-09-11 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0077_dumpnarrative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "VirusTotal"),
                    (2, "MISP"),
                    (3, "Ollama"),
                    (4, "Webhook"),
                    (5, "Slack"),
                    (6, "Email"),
                    (7, "AbuseIPDB"),
                    (8, "AlienVault OTX"),
                    (9, "GreyNoise"),
                ],
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="DumpIOC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ioc_type",
                    models.CharField(
                        choices=[
                            ("ip", "IP Address"),
                            ("domain", "Domain Name"),
                            ("url", "URL"),
                            ("hash_sha256", "SHA256 Hash"),
                            ("hash_md5", "MD5 Hash"),
                            ("yara", "YARA Rule Match"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                ("source_plugin", models.CharField(max_length=150)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("enrichment", models.JSONField(blank=True, default=dict)),
                ("is_malicious", models.BooleanField(default=False)),
                ("threat_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dump",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iocs",
                        to="website.dump",
                    ),
                ),
            ],
            options={
                "ordering": ("-threat_score", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["dump", "ioc_type"],
                        name="website_dum_dump_id_818a7a_idx",
                    ),
                    models.Index(
                        fields=["dump", "is_malicious"],
                        name="website_dum_dump_id_57ba3b_idx",
                    ),
                ],
                "unique_together": {("dump", "ioc_type", "value")},
            },
        ),
    ]
