# Generated by Django 6.1.1 on 2026-09-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0078_dumpioc_alter_service_name"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dumpioc",
            new_name="website_dum_dump_id_bd3af1_idx",
            old_name="website_dum_dump_id_818a7a_idx",
        ),
        migrations.RenameIndex(
            model_name="dumpioc",
            new_name="website_dum_dump_id_44da27_idx",
            old_name="website_dum_dump_id_57ba3b_idx",
        ),
        migrations.AddField(
            model_name="dump",
            name="symbol_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ok", "OK"),
                    ("missing", "Missing"),
                    ("wrong_kernel", "Wrong Kernel"),
                    ("unsupported", "Unsupported"),
                    ("stale", "Stale"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
                null=True,
            ),
        ),
    ]
