# Generated by Django 6.1.1 on 2026-09-11 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0079_dump_symbol_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playbook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("playbook_id", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "operating_system",
                    models.CharField(
                        choices=[
                            ("Linux", "Linux"),
                            ("Windows", "Windows"),
                            ("Mac", "Mac"),
                            ("Other", "Other"),
                        ],
                        default="Windows",
                        max_length=10,
                    ),
                ),
                ("icon", models.CharField(default="fa-bolt", max_length=50)),
                ("color", models.CharField(default="blue", max_length=50)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plugins",
                    models.ManyToManyField(
                        blank=True, related_name="playbooks", to="website.plugin"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_playbooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
