name: docker-compose-actions-workflow
on:
  push:
    branches:
      - master
    tags:
      - "v*"
env:
  REGISTRY: ghcr.io
  # Define a new job-level environment variable for the lowercase repository path
  LOWER_REPO: ${{ github.repository | lower }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Use the simple, uppercase repository structure here.
          # The lowercase conversion is now handled by the LOWER_REPO env variable.
          - dockerfile: Dockerfile
            context_path: ./compose/local/django
            image_name: orochi_django # Only the suffix needed
          - dockerfile: Dockerfile
            context_path: ./compose/local/dask
            image_name: orochi_worker # Only the suffix needed
          - dockerfile: Dockerfile
            context_path: ./compose/local/nginx
            image_name: orochi_nginx # Only the suffix needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context_path }}
          
          file: ${{ matrix.context_path }}/${{ matrix.dockerfile }}
          
          platforms: linux/amd64,linux/arm64
          
          push: ${{ github.event_name != 'pull_request' }}
          
          # Construct the full, lowercase image tag using the new environment variable
          tags: |
            ${{ env.REGISTRY }}/${{ env.LOWER_REPO }}_${{ matrix.image_name }}:latest
            ${{ env.REGISTRY }}/${{ env.LOWER_REPO }}_${{ matrix.image_name }}:${{ github.sha }}
