name: docker-compose-actions-workflow
on:
  push:
    branches:
      - master
    tags:
      - "v*"
env:
  REGISTRY: ghcr.io
  # This environment variable is not strictly needed but kept for context:
  IMAGE_NAME: ${{ github.repository }} 

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # IMPORTANT FIX: Use github.repository | lower to ensure the registry path is all lowercase.
          - dockerfile: Dockerfile
            context_path: ./compose/local/django
            image: ghcr.io/${{ github.repository | lower }}_django
          - dockerfile: Dockerfile
            context_path: ./compose/local/dask
            image: ghcr.io/${{ github.repository | lower }}_worker
          - dockerfile: Dockerfile
            context_path: ./compose/local/nginx
            image: ghcr.io/${{ github.repository | lower }}_nginx
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # The 'Extract metadata' step is correctly omitted.

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          # Use context_path for the build context
          context: ${{ matrix.context_path }}
          
          # Use the full path to the Dockerfile
          file: ${{ matrix.context_path }}/${{ matrix.dockerfile }}
          
          platforms: linux/amd64,linux/arm64
          
          push: ${{ github.event_name != 'pull_request' }}
          
          # Use the corrected, lowercase image tag
          tags: |
            ${{ matrix.image }}:latest
            ${{ matrix.image }}:${{ github.sha }}
