name: docker-compose-actions-workflow
on:
  push:
    branches:
      - master
    tags:
      - "v*"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Define context_path and dockerfile separately for clean path resolution
          - dockerfile: Dockerfile
            context_path: ./compose/local/django
            image: ghcr.io/LDO-CERT/orochi_django
          - dockerfile: Dockerfile
            context_path: ./compose/local/dask
            image: ghcr.io/LDO-CERT/orochi_worker
          - dockerfile: Dockerfile
            context_path: ./compose/local/nginx
            image: ghcr.io/LDO-CERT/orochi_nginx
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # The 'Extract metadata' step has been removed

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          # Use context_path for the build context (root folder for COPY/ADD)
          context: ${{ matrix.context_path }}
          
          # Use the full path to the Dockerfile
          file: ${{ matrix.context_path }}/${{ matrix.dockerfile }}
          
          platforms: linux/amd64,linux/arm64
          
          push: ${{ github.event_name != 'pull_request' }}
          
          # Use explicit tags to ensure the multi-arch manifest list is correctly created
          tags: |
            ${{ matrix.image }}:latest
            ${{ matrix.image }}:${{ github.sha }}
          
          # The labels output is no longer needed
