name: docker-compose-actions-workflow
on:
  push:
    branches:
      - master
    tags:
      - "v*"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./compose/local/django/Dockerfile
            image: ghcr.io/LDO-CERT/orochi_django
          - dockerfile: ./compose/local/dask/Dockerfile
            image: ghcr.io/LDO-CERT/orochi_worker
          - dockerfile: ./compose/local/nginx/Dockerfile
            image: ghcr.io/LDO-CERT/orochi_nginx
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Removed: The 'Extract metadata' step is deleted to use explicit tags below.

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          # Fix: Sets the context to the Dockerfile's folder (e.g., ./compose/local/django/)
          # to correctly resolve COPY/ADD commands.
          context: ${{ matrix.dockerfile | replace 'Dockerfile' '' }}
          file: ${{ matrix.dockerfile }}

          # Explicitly set platforms for the multi-arch manifest
          platforms: linux/amd64,linux/arm64

          push: ${{ github.event_name != 'pull_request' }}

          # Fix: Use explicit tags to ensure the multi-arch manifest list is created
          # and correctly associated with the 'latest' tag.
          tags: |
            ${{ matrix.image }}:latest
            ${{ matrix.image }}:${{ github.sha }}

          # Removed: labels: ${{ steps.meta.outputs.labels }}
