name: docker-compose-actions-workflow
on:
  push:
    branches:
      - master
    tags:
      - "v*"
env:
  REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ubuntu-latest
    # Define the lowercase repository path here to avoid parsing errors in the matrix
    env:
      LOWER_REPO: ${{ github.repository | lower }}
      
    strategy:
      fail-fast: false
      matrix:
        include:
          # Use simple string values in the matrix to avoid parser errors
          - dockerfile: Dockerfile
            context_path: ./compose/local/django
            image_suffix: django
          - dockerfile: Dockerfile
            context_path: ./compose/local/dask
            image_suffix: worker
          - dockerfile: Dockerfile
            context_path: ./compose/local/nginx
            image_suffix: nginx
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          # Use context_path for the build context
          context: ${{ matrix.context_path }}
          
          # Use the full path to the Dockerfile
          file: ${{ matrix.context_path }}/${{ matrix.dockerfile }}
          
          platforms: linux/amd64,linux/arm64
          
          push: ${{ github.event_name != 'pull_request' }}
          
          # Construct the full, correct, lowercase image tag using the new environment variable
          tags: |
            ${{ env.REGISTRY }}/${{ env.LOWER_REPO }}_${{ matrix.image_suffix }}:latest
            ${{ env.REGISTRY }}/${{ env.LOWER_REPO }}_${{ matrix.image_suffix }}:${{ github.sha }}
