name: docker-compose-actions-workflow
on:
  push:
    branches:
      - master
    tags:
      - "v*"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    # 🎯 CONCURRENCY BLOCK ADDED HERE
    concurrency:
      # This group name ensures only one workflow run happens at a time for this branch
      group: ${{ github.workflow }}-${{ github.ref }}
      # If a new run is started, the older one is cancelled
      cancel-in-progress: true
      
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./compose/local/django/Dockerfile
            image: ghcr.io/LDO-CERT/orochi_django
          - dockerfile: ./compose/local/dask/Dockerfile
            image: ghcr.io/LDO-CERT/orochi_worker
          - dockerfile: ./compose/local/nginx/Dockerfile
            image: ghcr.io/LDO-CERT/orochi_nginx
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (with layer caching) 🚀
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.dockerfile | replace 'Dockerfile' '' }}
          file: ${{ matrix.dockerfile }}

          platforms: linux/amd64,linux/arm64

          push: ${{ github.event_name != 'pull_request' }}
          
          # Layer Caching for faster builds (as discussed previously)
          cache-from: type=gha
          cache-to: type=gha,mode=max 

          tags: |
            ${{ matrix.image }}:latest
            ${{ matrix.image }}:${{ github.sha }}
